
author: Ahmed Sharif Khan Noor
start_year: 2023
current_year: {{ site.time | date: "%Y" }}

# Site settings
title: Harmony
email: Harmony@gmail.com
number: 0123 345 6789
address: New York, NY 10012, US
description: >- # this means to ignore newlines until "baseurl:"
   Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
baseurl: "/harmony" # the subpath of your site, e.g. /blog
url: "https://ahmedsharifkhan.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

permalink: /:categories/:year/:month/:day/:title

facebook_username: https://www.facebook.com/ahmedsharifkhannoor
twitter_username: https://www.twitter.com/maxnoor87
instagram_username: https://www.instagram.com/ahmedsharifkhannoor
linkedin_username: https://www.linkedin.com/in/ahmedsharifkhannoor
github_username: https://www.github.com/ahmedsharifkhannoor
youtube_username: https://www.youtube.com/channel/UCBfIS1RdIpSoS1e75LXJuxw


# _config.yml
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: "/blog/:title/"

# Collections
collections:
  authors:
    output: true
    permalink: /authors/:path/

# Modify Navigation Configuration:
# Navigation
header_pages:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Authors
    url: /authors




# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag



 # This will require each of these gems automatically.

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
